# Generated by Django 2.2.5 on 2019-10-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog_instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('push_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='leave_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('mail_addr', models.TextField()),
                ('phone', models.TextField()),
                ('content', models.TextField()),
                ('push_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
