# Generated by Django 3.0.1 on 2019-12-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191223_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_instance',
            name='blog_img',
            field=models.ImageField(default='', max_length=1000, upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
