# Generated by Django 3.0.1 on 2019-12-24 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_instance_blog_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_instance',
            name='categary',
            field=models.TextField(default=''),
        ),
    ]
