# Generated by Django 3.0.1 on 2019-12-24 23:38

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191225_0734'),
    ]

    operations = [
        migrations.CreateModel(
            name='program_instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.TextField()),
                ('title_2', models.TextField()),
                ('program_img', models.ImageField(default='', max_length=1000, upload_to='uploads/% Y/% m/% d/')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('push_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
    ]
