# Generated by Django 2.1.7 on 2019-12-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_program_instance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program_instance',
            options={'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.AddField(
            model_name='blog_instance',
            name='author',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='blog_instance',
            name='blog_img',
            field=models.ImageField(default='uploads/default_blog.png', help_text='图片的大小务必是342x215', max_length=1000, upload_to='uploads/20191226171318/'),
        ),
        migrations.AlterField(
            model_name='blog_instance',
            name='categary',
            field=models.CharField(choices=[('BUSINESS STORY', 'BUSINESS STORY'), ('STUDENT VOICE', 'STUDENT VOICE'), ('CULTURAL ADVENTURE', 'CULTURAL ADVENTURE')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='program_instance',
            name='program_img',
            field=models.ImageField(default='uploads/default_program.png', help_text='图片的大小务必是624x397', max_length=1000, upload_to='uploads/20191226171318/'),
        ),
    ]
