# Generated by Django 2.1.7 on 2020-01-03 02:43

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191226_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='program_instance',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='program_instance',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
        migrations.AddField(
            model_name='program_instance',
            name='learning_objectives',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
        migrations.AddField(
            model_name='program_instance',
            name='ltinerary',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
        migrations.AlterField(
            model_name='blog_instance',
            name='blog_img',
            field=models.ImageField(default='uploads/default_blog.png', help_text='图片的大小务必是342x215', max_length=1000, upload_to='uploads/20200103104325/'),
        ),
        migrations.AlterField(
            model_name='program_instance',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='program_instance',
            name='program_img',
            field=models.ImageField(default='uploads/default_program.png', help_text='图片的大小务必是624x397', max_length=1000, upload_to='uploads/20200103104325/'),
        ),
    ]
