# Generated by Django 2.1.7 on 2020-01-03 02:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200103_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_instance',
            name='blog_img',
            field=models.ImageField(default='uploads/default_blog.png', help_text='图片的大小务必是342x215', max_length=1000, upload_to='uploads/20200103104529/'),
        ),
        migrations.AlterField(
            model_name='program_instance',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
        migrations.AlterField(
            model_name='program_instance',
            name='program_img',
            field=models.ImageField(default='uploads/default_program.png', help_text='图片的大小务必是624x397', max_length=1000, upload_to='uploads/20200103104529/'),
        ),
    ]
