# Generated by Django 3.0.3 on 2020-02-13 07:49

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200213_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_instance',
            name='author_cn',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog_instance',
            name='content_cn',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
        migrations.AddField(
            model_name='blog_instance',
            name='title_cn',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='blog_instance',
            name='blog_img',
            field=models.ImageField(default='uploads/default_blog.png', help_text='图片的大小务必是342x215', max_length=1000, upload_to='uploads/20200213154934/'),
        ),
        migrations.AlterField(
            model_name='program_instance',
            name='program_img',
            field=models.ImageField(default='uploads/default_program.png', max_length=1000, upload_to='uploads/20200213154934/'),
        ),
        migrations.AlterField(
            model_name='testimonials_instance',
            name='img_src',
            field=models.ImageField(default='uploads/default_program.png', max_length=1000, upload_to='uploads/20200213154934/'),
        ),
    ]
